<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="Mediamatiker EFZ, Bildungszentrum Zürichsee, Horgen">
<meta name="author" content="daniel.garavaldi@bzz.ch">
<!-- Bootstrap -->
<?php
//require_once(__DIR__ . '/../lib/Navigation.php');
//$nav = new Navigation();
//echo $nav->getSiteTitle();
//$path = "../../../../../";
$path = "./";
?>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<link href=<?=$path. "inc/vendor/highlight/css/highlight.agate.css" ?> media="screen" rel="stylesheet">
<script type="text/javascript" src=<?=$path. "inc/vendor/highlight/js/highlight.pack.js" ?>></script>
<script>hljs.initHighlightingOnLoad();</script>
<!-- Custom styles for this template -->
<link href=<?=$path. "inc/theme.css" ?> rel="stylesheet">
<!-- Custom scripts (JavaScripts) for this template -->
<script type="text/javascript" src=<?=$path. "inc/script/ui.js" ?>></script>
<script type="application/javascript"
        src=<?=$path. "inc/script/handlebars-v4.0.11.js" ?>></script>